#!/bin/bash
set -e
cd "$(dirname "$0")/../.."

# check dependencies
ruby -v > /dev/null    || (echo "ruby must be installed"; exit 1)

major_minor_version="$(ruby -e 'puts RUBY_VERSION.split(".")[0, 2].join(".")')"
gemfile_lock="gemfiles/Gemfile.${major_minor_version}.lock"
if [ -f "$gemfile_lock" ]; then
  cp -v "$gemfile_lock" Gemfile.lock
else
  rm -vf Gemfile.lock
fi

bundle -v > /dev/null  || (echo "bundler must be installed"; exit 1)

# TODO: update to test against updates dependencies as well
bundle install

if [ ! -f "$gemfile_lock" ]; then
  cp -v Gemfile.lock "$gemfile_lock"
fi

cd test

key_relative_path="tmp/.docraptor_key"
key_path="../$key_relative_path"

# runs a test file with PASS/FAIL message
run_test() {
  test_name="$1"
  if [[ "$DOCRAPTOR_KEY" == "" ]] && [ -f "$key_path" ]; then
    (export DOCRAPTOR_KEY="$(cat "$key_path")" && run_test $1)
    test_name="$test_name (without "$key_relative_path")"
  else
    test_name="$test_name (with "$key_relative_path")"
  fi
  ruby $1 && echo "PASS $test_name" || (echo "FAIL $test_name"; exit 1)
}

if [ "$1" == "" ]; then
  for test in $(ls *.rb); do
    run_test $test
  done
else
  run_test $1.rb
fi
