# -*- encoding: utf-8 -*-

=begin
#DocRaptor

#A native client library for the DocRaptor HTML to PDF/XLS service.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "docraptor/version"

Gem::Specification.new do |s|
  s.name        = "docraptor"
  s.version     = DocRaptor::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Expected Behavior"]
  s.email       = ["support@docraptor.com"]
  s.homepage    = "https://github.com/docraptor/docraptor-ruby"
  s.summary     = "A wrapper for the DocRaptor HTML to PDF/XLS service."
  s.description = "A native client library for the DocRaptor HTML to PDF/XLS service."
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.5"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `git ls-files`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `git ls-files spec test`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
