=begin
#DocRaptor

#A native client library for the DocRaptor HTML to PDF/XLS service.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DocRaptor::AsyncDoc
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe DocRaptor::AsyncDoc do
  let(:instance) { DocRaptor::AsyncDoc.new }

  describe 'test an instance of AsyncDoc' do
    it 'should create an instance of AsyncDoc' do
      expect(instance).to be_instance_of(DocRaptor::AsyncDoc)
    end
  end
  describe 'test attribute "status_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
