=begin
#DocRaptor v1

OpenAPI spec version: 1.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for DocRaptor::DocApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DocApi' do
  before do
    # run before each test
    @instance = DocRaptor::DocApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DocApi' do
    it 'should create an instact of DocApi' do
      expect(@instance).to be_instance_of(DocRaptor::DocApi)
    end
  end

  # unit tests for create_async_doc
  # 
  # Creates a document asynchronously. You must use a callback url or the the returned status id and the status api to find out when it completes. Then use the download api to get the document. 
  # @param doc The document to be created.
  # @param [Hash] opts the optional parameters
  # @return [AsyncDoc]
  describe 'create_async_doc test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_doc
  # 
  # Creates a document synchronously. 
  # @param doc The document to be created.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'create_doc test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_async_doc
  # 
  # Downloads a document. 
  # @param id The download_id returned from status request or a callback.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_async_doc test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_async_doc_status
  # 
  # Check on the status of an asynchronously created document. 
  # @param id The status_id returned when creating an asynchronous document.
  # @param [Hash] opts the optional parameters
  # @return [AsyncDocStatus]
  describe 'get_async_doc_status test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
