require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DocRaptor::AsyncDoc
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AsyncDoc' do
  before do
    # run before each test
    @instance = DocRaptor::AsyncDoc.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AsyncDoc' do
    it 'should create an instact of AsyncDoc' do
      expect(@instance).to be_instance_of(DocRaptor::AsyncDoc)
    end
  end
  describe 'test attribute "status_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

