=begin
#DocRaptor v1

#A native client library for the DocRaptor HTML to PDF/XLS service.

OpenAPI spec version: 1.4.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DocRaptor::HostedDoc
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'HostedDoc' do
  before do
    # run before each test
    @instance = DocRaptor::HostedDoc.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HostedDoc' do
    it 'should create an instance of HostedDoc' do
      expect(@instance).to be_instance_of(DocRaptor::HostedDoc)
    end
  end
  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "download_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "download_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "number_of_pages"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
