#!/bin/bash
set -e
[[ "$TRACE" == "true" ]] && set -x
cd "$(dirname "$0")/.."

echo "Removing trailing whitespace..."
find lib -name "*.rb" -type f -exec sed -E -i '' 's/[[:space:]]+$//g' {} +

echo "Fixing gemspec to work around swagger..."
ruby script/fix_gemspec.rb

if compgen -G "patches/*.patch" > /dev/null; then
  echo "Apply patches to generated code"
  git apply --verbose patches/*.patch
fi
