#!/bin/bash
set -e
cd "$(dirname "$0")/.."

setup_echo() {
  echo "[script/setup] $1"
}

setup_error() {
  echo "[script/setup][ERROR] $1"
}

brew_install() {
  setup_echo "Installing $1..."
  brew list --formula "$1" > /dev/null || brew install --formula "$1"
}

brew_cask_install() {
  setup_echo "Installing cask $1..."
  brew list --cask "$1" &> /dev/null || brew install --cask "$1"
}

brew_cask_install docker
brew_install docker

# Avoid a warning message (vs. --overwrite)
brew unlink docker && brew link docker

tput bold    # bold text
tput setaf 2 # green text
setup_echo "****************************************************************"
setup_echo "*                                                              *"
setup_echo "*                         Good to go!                          *"
setup_echo "*                                                              *"
setup_echo "****************************************************************"
tput sgr0    # reset to default text
