#!/bin/sh
set -e
cd "`dirname \"$0\"`/.."

# check dependencies
ruby -v > /dev/null    || (echo "ruby must be installed"; exit 1)
bundler -v > /dev/null || (echo "bundler must be installed"; exit 1)

bundle install

cd test

# runs a test file with PASS/FAIL message
run_test() {
  ruby $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
}

if [ "$1" == "" ]; then
  for test in $(ls *.rb); do
    run_test $test
  done
else
  run_test $1.rb
fi
