#!/bin/bash
set -e
cd "$(dirname "$0")/.."

# check dependencies
ruby -v > /dev/null    || (echo "ruby must be installed"; exit 1)
bundler -v > /dev/null || (echo "bundler must be installed"; exit 1)

bundle install

# runs a test file with PASS/FAIL message
run_test() {
  ruby $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
}

run_tests() {
  runtime_env="$1"
  if time script/docker -i "$runtime_env" /app/script/inside_container/test; then
    tput bold    # bold text
    tput setaf 2 # green text
    echo "======================================"
    echo "$runtime_env Passed"
    echo "======================================"
    tput sgr0    # reset to default text
    return 0
  else
    tput bold    # bold text
    tput setaf 1 # red text
    echo "======================================"
    echo "$runtime_env FAILED"
    echo "======================================"
    tput sgr0    # reset to default text
    return 1
  fi
}

success="true"

for runtime_env in $(cat .runtime-environments | grep -v '^#'); do
  echo
  echo
  echo "Testing runtime env $runtime_env"
  run_tests "$runtime_env" || success="false"
done

if [ $success == "true" ]; then
  tput bold    # bold text
  tput setaf 2 # green text
  echo "======================================"
  echo "=              Passed                ="
  echo "======================================"
  tput sgr0    # reset to default text
  exit 0
else
  tput bold    # bold text
  tput setaf 1 # red text
  echo "======================================"
  echo "=              FAILED                ="
  echo "======================================"
  tput sgr0    # reset to default text
  exit 1
fi
